version: '3'
services:
  postgres:
    image: jharner/rspark-postgres:0.9.8
    restart: always
    ports:
      - "5432:5432"     # Postgres
    volumes:
      - ./data/pg-data:/opt/pg-data
      
      
  hadoop:
    image: jharner/rspark-hadoop:0.9.8
    restart: always
    volumes:
      - ./data/hadoop:/opt/hadoop
    ports:
      - "9000:9000"     # Hadoop
      - "50070:50070"   # Hadoop UI Access
      
   hive:
    image: jharner/rspark-hive:0.9.8
    restart: always
    ports:
      - "10000:10000"   # Hive
    depends_on:
      - hadoop   
         
  rstudio:
    image: jharner/rspark-rstudio:0.9.8
    restart: always
    environment:
      - PASSWORD=rstudiojh
    volumes:
      - ./data/rstudio:/home/rstudio
    ports:
      - "8787:8787"     # Rstudio UI
      - "4040:4040"     # Spark Web UI
    depends_on: 
      - hadoop
      - hive
