version: '3.5'
services:
  postgres:
    image: jharner/rspark-postgres:0.9.9
    container_name: postgres
    hostname: postgres
    restart: always
    ports:
      - "5432:5432"     # Postgres
    volumes:
      - ./data/pg-data:/opt/pg-data
  hadoop:
    image: jharner/rspark-hadoop:0.9.9
    container_name: hadoop
    hostname: hadoop
    restart: always
    volumes:
      - ./data/hadoop:/opt/hadoop
    ports:
      - "9000:9000"     # Hadoop
      - "50070:50070"   # Hadoop UI Access
  hive:
    image: jharner/rspark-hive:0.9.9
    container_name: hive
    hostname: hive
    restart: always
    ports:
      - "10000:10000"   # Hive
    depends_on:
      - hadoop
  rstudio:
    image: jharner/rspark-rstudio:0.9.9
    container_name: rstudio
    hostname: rstudio
    restart: always
    environment:
      - PASSWORD=rstudiojh
    volumes:
      - ./data/rstudio:/home/rstudio
    ports:
      - "8787:8787"     # Rstudio UI
      - "4040:4040"     # Spark Web UI
    depends_on: 
      - hadoop
      - hive
