version: '3.5'
services:

  postgres:
    image: jharner/rspark-postgres:1.0.5
    container_name: postgres
    hostname: postgres
    restart: always
    ports:
      - "5432:5432"     # Postgres
    volumes:
      - rspark_pgdata:/opt/pg-data

  hadoop:
    image: jharner/rspark-hadoop:1.0.5
    container_name: hadoop
    hostname: hadoop
    restart: always
    ports:
      - "9000:9000"     # Hadoop
      - "50070:50070"   # Hadoop UI
    volumes:
      - rspark_hadoopdata:/opt/hadoop

  hive:
    image: jharner/rspark-hive:1.0.5
    container_name: hive
    hostname: hive
    restart: always
    ports:
      - "10000:10000"   # Hive
      - "9999:9999"     # Hive UI
    depends_on:
      - hadoop
      - postgres

  rstudio:
    image: jharner/rspark-rstudio:1.0.5
    container_name: rstudio
    hostname: rstudio
    restart: always
    environment:
      - PASSWORD=rstudiojh
    ports:
      - "8787:8787"     # RStudio UI
      - "4040:4040"     # Spark Web UI
    volumes:
      - rspark_rstudio:/home/rstudio
#       - ./rspark-tutorial:/home/rstudio/rspark_tutorial
    depends_on: 
      - hadoop
      - hive

volumes:
  rspark_hadoopdata:
  rspark_rstudio:
  rspark_pgdata:
  rspark_sparkdata:
